author: SwearWord
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: org.getchunky.chunkyvillage.ChunkyVillage
name: ChunkyVillage
startup: postworld
url: http://getchunky.org/
version: ${build.number}
depend: [Chunky]
commands:
    town:
        description: Displays town information and contains other commands.
        aliases: t
    resident:
        description: Displays resident information and contains other commands.
        aliases: [r,res]
    admin:
        description: Modify all towns.
        aliases: [a]
permissions:
    chunky.town.create:
        description: Create new towns.
        default: op
    chunky.town.warmup:
        description: Require warmup for /t spawn.
        default: true
    chunky.town.admin:
        description: Use /admin to manage towns.
        default: op
    chunky.town.admin.teleport:
        description: Teleport without restrictions.
        default: op
    chunky.town.stance:
        description: Set stance of a town.
        default: true
